more progress on joetoolkit - complete with copyright/licence checks
Signed-off-by: JosephBrendler <joseph.brendler@gmail.com>

diff --git a/dev-util/joetoolkit/devtools/validate_scripts b/dev-util/joetoolkit/devtools/validate_scripts
--- a/dev-util/joetoolkit/devtools/validate_scripts
+++ b/dev-util/joetoolkit/devtools/validate_scripts
@@ -8,6 +8,7 @@
 # shellcheck source=/usr/sbin/script_header_joetoo_extended
 # shellcheck source=/usr/sbin/script_header_joetoo_unicode
 source /usr/sbin/script_header_joetoo
+source /usr/sbin/setTIMEFORMAT.hdr
 
 #-----[ global variables ]-------------------------------------------------------------------
 
@@ -288,10 +289,10 @@ millis2time()   # (POSIX) convert integer ms to time format
   # in POSIX shell (( x % divisor )) produces the "remainder - fractional part" of division
   _mt_mmm=$(( _mt_ms % 1000 )) || mt_ret=1  #..................# millisecond part = remainder when max whole # of seconds is removed
 
-  _mt_sec=$(( _mt_ms / 1000 )) || mt_ret=$(( mt_ret | 2 ))    # integer number of seconds in elapsed time
-  _mt_ss=$((  _mt_sec % 60  ))  || mt_ret=$(( mt_ret | 4 ))   # seconds part = remainder when max whole # of minutes is removed
+  _mt_sec=$(( _mt_ms / 1000 )) || mt_ret=$(( mt_ret | 2 ))     # integer number of seconds in elapsed time
+  _mt_ss=$((  _mt_sec % 60  ))  || mt_ret=$(( mt_ret | 4 ))    # seconds part = remainder when max whole # of minutes is removed
 
-  _mt_min=$(( _mt_sec / 60  ))  || mt_ret=$(( mt_ret | 8 ))   # integer number of minutes in elapsed time
+  _mt_min=$(( _mt_sec / 60  ))  || mt_ret=$(( mt_ret | 8 ))    # integer number of minutes in elapsed time
   _mt_mm=$((  _mt_min % 60  ))  || mt_ret=$(( mt_ret | 16 ))   # minutes part = remainder when max whole # of hrs is removed
 
   _mt_hrs=$(( _mt_min / 60  ))  || mt_ret=$(( mt_ret | 32 ))   # integer number of hours in elapsed time
@@ -380,10 +381,11 @@ for x in "${target_array[@]}" ; do
         if [ $TIMERS ] ; then
             j_msg "-${debug}" -p "full command: [time $executable ${arguments[*]} $x]"
             # Note: use bash PIPESTATUS array to get exit status of the command, not the grep
+            #   use setTIMEFORMAT.hdr (sourced above) function to customize time output (-l = long format)
+            setTIMEFORMAT -l
             time "$executable" "${arguments[@]}" "$x" 2>&1 | grep -v 'syntax OK'
-            if [ "${PIPESTATUS[0]}" -ne 0 ] ; then
-                 j_msg "-${err}" -m "$x failed syntax check"
-            fi
+            if [ "${PIPESTATUS[0]}" -ne 0 ] ; then j_msg "-${err}" -m "$x failed syntax check"; fi
+            unset TIMEFORMAT
         else
             j_msg "-${debug}" -p "full command: [$executable ${arguments[*]} $x]"
             # Note: use bash PIPESTATUS array to get exit status of the command, not the grep
@@ -399,8 +401,11 @@ for x in "${target_array[@]}" ; do
         if [ $TIMERS ] ; then
             j_msg "-${debug}" -p "full command: [time $executable ${arguments[*]} $x]"
             j_msg "-${notice}" -mp -M "$idx_magnifying_glass_right" "checking $x ..."
+            #   use setTIMEFORMAT.hdr (sourced above) function to customize time output (-l = long format)
+            setTIMEFORMAT -l
             time "$executable" "${arguments[@]}" "$x" 2>&1 | grep -v 'syntax OK'
             result="${PIPESTATUS[0]}"
+            unset TIMEFORMAT
         else
             j_msg "-${debug}" -p "full command: [time $executable ${arguments[*]} $x]"
             j_msg "-${notice}" -mp -M "$idx_magnifying_glass_right" "checking $x ..."
diff --git a/dev-util/joetoolkit/joetoolkit/kernel-clean b/dev-util/joetoolkit/joetoolkit/kernel-clean
--- a/dev-util/joetoolkit/joetoolkit/kernel-clean
+++ b/dev-util/joetoolkit/joetoolkit/kernel-clean
@@ -1,7 +1,8 @@
 #!/bin/bash
+# Copyright 2014-2026 Joseph Brendler
+# SPDX-License-Identifier: GPL-3.0-or-later
+
 # clean out old kernel residue
-#
-# joe brendler, 2 Aug 2014
 #
 source /usr/sbin/script_header_joetoo
 
@@ -12,7 +13,7 @@ if [ -f /etc/joetoolkit/BUILD ]; then . /etc/joetoolkit/BUILD; else BUILD=0.0.1;
 get_yn_reply()
 {
   unset reply
-  yn_prompt  "delete $1 residual for of kernel "$2" [y/n]? "
+  yn_prompt  "delete $1 residual for of kernel $2 [y/n]? "
   case "$answer" in
     [yY]*) return 0 ;;
     [nN]*) return 1 ;;
@@ -23,47 +24,51 @@ get_yn_reply()
 
 clean_residue()
 {
-  j_msg -${notice} -p "sources found:"
-  ls -al /usr/src/linux-*$1*
-  if get_yn_reply "sources" $1; then
-    j_msg -${notice} -p "deleting sources residual for kernel $1"
-    rm -rfv /usr/src/linux-*$1*
+  [ $# -eq 0 ] && die "selector \$1 empty [$1]"
+  [ $# -eq 1 ] || die "invalid args in clean_residue [$*]"
+  selector="$1"
+  j_msg "-${notice}" -p "sources found:"
+  ls -al /usr/src/linux-*${selector}*
+  if get_yn_reply "sources" "${selector}"; then
+    j_msg "-${notice}" -p "deleting sources residual for kernel ${selector}"
+    rm -rfv /usr/src/linux-*${selector}*
   else
-    j_msg -${notice} -p "Aborting at user direction"
+    j_msg "-${notice}" -p "Aborting at user direction"
     exit 1
   fi
 
-  j_msg -${notice} -p "modules found:"
-  ls -al /lib/modules/*$1*
-  if get_yn_reply "modules" $1; then
-    j_msg -${notice} -p "deleting modules residual for kernel $1"
-    rm -rfv /lib/modules/*$1*
+  j_msg "-${notice}" -p "modules found:"
+  ls -al /lib/modules/*${selector}*
+  if get_yn_reply "modules" "${selector}"; then
+    j_msg "-${notice}" -p "deleting modules residual for kernel ${selector}"
+    rm -rfv /lib/modules/*${selector}*
   else
-    j_msg -${notice} -p "Aborting at user direction"
+    j_msg "-${notice}" -p "Aborting at user direction"
     exit 1
   fi
 
-  j_msg -${notice} -p "boot images found:"
-  ls -al /boot/*$1*
-  if get_yn_reply "images" $1; then
-    j_msg -${notice} -p "deleting images residual for kernel $1"
-    rm -rfv /boot/*$1*
+  j_msg "-${notice}" -p "boot images found:"
+  ls -al /boot/*${selector}*
+  if get_yn_reply "images" "${selector}"; then
+    j_msg "-${notice}" -p "deleting images residual for kernel ${selector}"
+    rm -rfv /boot/*${selector}*
   else
-    j_msg -${notice} -p "Aborting at user direction"
+    j_msg "-${notice}" -p "Aborting at user direction"
     exit 1
   fi
 }
 
 #---[ main script ]---------------------------
+checkroot
 separator "$(hostname)" "${PN}-${BUILD}"
 
 if [[ -z "$1" ]]
 then
-  j_msg -${notice} -p "listing kernel versions found..."
-  j_msg -${notice} -p "sources:" && ls -al /usr/src/
-  j_msg -${notice} -p "modules:" && ls -al /lib/modules/
-  j_msg -${notice} -p "images:"  && ls -al /boot/
+  j_msg "-${notice}" -p "listing kernel versions found..."
+  j_msg "-${notice}" -p "sources:" && ls -al /usr/src/
+  j_msg "-${notice}" -p "modules:" && ls -al /lib/modules/
+  j_msg "-${notice}" -p "images:"  && ls -al /boot/
 else
-  j_msg -${notice} -p "cleaning residue of kernels identified by filter [$1]"
+  j_msg "-${notice}" -p "cleaning residue of kernels identified by filter [$1]"
   clean_residue "$1"
 fi
diff --git a/dev-util/joetoolkit/joetoolkit/nextcloud_allow_local_remote_servers b/dev-util/joetoolkit/joetoolkit/nextcloud_allow_local_remote_servers
--- a/dev-util/joetoolkit/joetoolkit/nextcloud_allow_local_remote_servers
+++ b/dev-util/joetoolkit/joetoolkit/nextcloud_allow_local_remote_servers
@@ -1,4 +1,7 @@
 #!/bin/bash
+# Copyright 2025-2026 Joseph Brendler
+# SPDX-License-Identifier: GPL-3.0-or-later
+
 source /usr/sbin/script_header_joetoo
 checkroot
 
@@ -26,7 +29,7 @@ nextcloud_dir="/var/www/localhost/htdocs/myCloud"
 silent=">/dev/null 2>&1"
 
 # don't set verbosity unless it is not already set (allow calling program to set it)
-[ -z $verbosity ] && verbosity=${notice}
+[ -z "$verbosity" ] && verbosity="${notice}"
 
 
 separator "$(hostname)" "${PN}-${BUILD}"
@@ -41,22 +44,22 @@ msg_sequence=(
 #-----[ main script ]--------------------------------------------------
 
 old_dir=$(pwd)
-j_msg -${notice} -p -n "${BYon}Moving to ${BMon}${nextcloud_dir}${Boff}"
+j_msg "-${notice}" -p -n "${BYon}Moving to ${BMon}${nextcloud_dir}${Boff}"
 cd "${nextcloud_dir}" || die "failed to move to ${nextcloud_dir}"
-right_status $TRUE ${notice}
-j_msg -${info} -m "${BWon}pwd: ${LBon}$(pwd)${Boff}"
+right_status $TRUE "${notice}"
+j_msg "-${info}" -m "${BWon}pwd: ${LBon}$(pwd)${Boff}"
 
 # mini run_sequence
 for ((i=0; i< ${#command_sequence[@]}; i++)) ; do
-    j_msg -${notice} -p -n "${BWon}running ${BGon}${msg_sequence[$i]}${Boff} ..."
+    j_msg "-${notice}" -p -n "${BWon}running ${BGon}${msg_sequence[$i]}${Boff} ..."
     eval "${command_sequence[$i]}" || die "failed: ${command_sequence[$i]}"
-    right_status $TRUE ${notice}
+    right_status $TRUE "${notice}"
 done
-j_msg -${notice} -mp "" # newline
+j_msg "-${notice}" -mp "" # newline
 
-j_msg -${notice} -p -n "${BYon}Moving back to ${BMon}${old_dir}${Boff}"
-cd ${nextcloud_dir} || die "failed to move to ${nextcloud_dir}"
-right_status $TRUE ${notice}
-j_msg -${info} -m "${BWon}pwd: ${LBon}$(pwd)${Boff}"
+j_msg "-${notice}" -p -n "${BYon}Moving back to ${BMon}${old_dir}${Boff}"
+cd "${nextcloud_dir}" || die "failed to move to ${nextcloud_dir}"
+right_status $TRUE "${notice}"
+j_msg "-${info}" -m "${BWon}pwd: ${LBon}$(pwd)${Boff}"
 
-j_msg -${notice} -p "${BGon}Done${Boff}"
+j_msg "-${notice}" -p "${BGon}Done${Boff}"
diff --git a/dev-util/joetoolkit/joetoolkit/nextcloud_check_version b/dev-util/joetoolkit/joetoolkit/nextcloud_check_version
--- a/dev-util/joetoolkit/joetoolkit/nextcloud_check_version
+++ b/dev-util/joetoolkit/joetoolkit/nextcloud_check_version
@@ -1,5 +1,8 @@
 #!/bin/bash
-# joetoo_cli_example - template app for joetoo CLI (c) Joe Brendler 2026-7789
+# Copyright 2025-2026 Joseph Brendler
+# SPDX-License-Identifier: GPL-3.0-or-later
+
+# nextcloud_check_version - rapid app developed from joetoo-cli-example - checks both ebuild and webapp installed versions
 
 script_header_installed_dir="/usr/sbin"
 #script_header_installed_dir=/home/joe/myUtilities/dev-util/script_header_joetoo
@@ -56,20 +59,20 @@ varlist="${varlist} BREAK bool.LOCALIZED yn.INITIALIZED_ME"
 get_webapp_installed_version() {
   if [ -z "$(find /var/www/localhost/htdocs/myCloud/ 2>/dev/null)" ]
   then
-    j_msg -${err} "nextcloud has not been installed by webapp-config"
+    j_msg "-${err}" "nextcloud has not been installed by webapp-config"
     exit
   else
     webapp_installed_version=$(basename $(find /var/www/localhost/htdocs/myCloud/ -maxdepth 1 -iname '.webapp-nextcloud*') | \
       sed 's/\.webapp-nextcloud-//')
-    j_msg -${notice} -p "webapp_installed_version: ${webapp_installed_version}"
+    j_msg "-${notice}" -p "webapp_installed_version: ${webapp_installed_version}"
   fi
 }
 
 get_emerged_versions() {
   ev_string="$(eix-update -q && eix -eIc nextcloud)"
-  j_msg -${debug} -p "ev_string: ${ev_string}"
+  j_msg "-${debug}" -p "ev_string: ${ev_string}"
   ev_string_l="${ev_string#*\(}"
-  j_msg -${debug} -p "ev_string_l: ${ev_string_l}"
+  j_msg "-${debug}" -p "ev_string_l: ${ev_string_l}"
   ev_string_lr="${ev_string_l%)*}"
 #  emerged_versions=$(echo ${answer} | awk -F[\(\)] '{print $3,$5,$7 }' )
   cut=""; version=""
@@ -77,20 +80,20 @@ get_emerged_versions() {
 #  while [ -n "${ev_string_lr}" ]
   while [[ "${ev_string_lr}" ==  *"("* ]]
   do
-    j_msg -${debug} -p "ev_string_lr: ${ev_string_lr}"
+    j_msg "-${debug}" -p "ev_string_lr: ${ev_string_lr}"
     # cut out the first parenthetically enclosed version
     cut="${ev_string_lr#*\(}"
-    j_msg -${debug} -p "  cut: ${cut}"
+    j_msg "-${debug}" -p "  cut: ${cut}"
     version="${cut%%)*}"
-    j_msg -${debug} -p "  version: ${version}"
+    j_msg "-${debug}" -p "  version: ${version}"
     emerged_version_list+=("${version}")
     msg="  emerged_version_list: [${emerged_version_list[@]}]"
-    j_msg -${debug} -p "${msg}"
+    j_msg "-${debug}" -p "${msg}"
     # re-set ev_string_lr to the remainder
     ev_string_lr="${cut#*)}"
   done
   msg="emerged_version_list: [${emerged_version_list[@]}]"
-  j_msg -${notice} -p "${msg}"
+  j_msg "-${notice}" -p "${msg}"
 }
 
 
@@ -98,13 +101,13 @@ check_emerged_versions() {
   for (( i=0; i<${#emerged_version_list[@]}; i++ ))
   do
     myver="${emerged_version_list[$i]}"
-    vercomp ${myver} ${webapp_installed_version} ; result=$?
-    j_msg -${notice} -p "${BWon}(emerged version) ${myver} $(show_result ${result}) ${BWon}${webapp_installed_version} (webapp-installed version)${Boff}"
-    case ${result} in
-      2 ) j_msg -${notice} -p "${BRon}  version $myver should be removed${Boff}" ;; # 2 is <
-      0 ) j_msg -${notice} -p "${BWon}  version $myver is current; no action required${Boff}" ;; # 0 is =
-      1 ) j_msg -${notice} -p "${BYon}  version $myver is newer ; please run ${BGon}nextcloud_upgrade ${myver}${Boff}" ; maybe_do_upgrade "${myver}" ;; # 1 is >
-      * ) j_msg -${err} "  error: bad version comparison"; exit ;;
+    vercomp "${myver}" "${webapp_installed_version}" ; result=$?
+    j_msg "-${notice}" -p "${BWon}(emerged version) ${myver} $(show_result ${result}) ${BWon}${webapp_installed_version} (webapp-installed version)${Boff}"
+    case "${result}" in
+      2 ) j_msg "-${notice}" -p "${BRon}  version $myver should be removed${Boff}" ;; # 2 is <
+      0 ) j_msg "-${notice}" -p "${BWon}  version $myver is current; no action required${Boff}" ;; # 0 is =
+      1 ) j_msg "-${notice}" -p "${BYon}  version $myver is newer ; please run ${BGon}nextcloud_upgrade ${myver}${Boff}" ; maybe_do_upgrade "${myver}" ;; # 1 is >
+      * ) j_msg "-${err}" "  error: bad version comparison"; exit ;;
     esac
   done
 }
@@ -116,8 +119,8 @@ maybe_do_upgrade() {
   yn_prompt "${BYon}  would you like to run ${BRon}# ${BGon}nextcloud_upgrade ${myver}${BYon} now?${Boff}"
   case ${answer:0:1} in
     [yY] ) eval "nextcloud_upgrade ${myver}" ;;
-    [nN] ) j_msg -${notice} -p "${BRon}Not${Boff} running nextcloud_upgrade; user declined" ;;
-    *    ) j_msg -${err} "error; bad response to upgrade question" ;;
+    [nN] ) j_msg "-${notice}" -p "${BRon}Not${Boff} running nextcloud_upgrade; user declined" ;;
+    *    ) j_msg "-${err}" "error; bad response to upgrade question" ;;
   esac
 }
 
@@ -128,16 +131,16 @@ app_configure || die "failed to app_configure"
 
 # re-assign varlist variables appended at the top of the script and thus
 # over-written by app_configure
-j_msg -${debug} -n -m "(re)assigning LOCALIZED"
+j_msg "-${debug}" -n -m "(re)assigning LOCALIZED"
 LOCALIZED=$TRUE
 handle_result $? "$(TrueFalse $LOCALIZED)" "failed to reassign LOCALIZED" "$debug"
-j_msg -${debug} -n -m "(re)assigning INITIALIZED_ME"
+j_msg "-${debug}" -n -m "(re)assigning INITIALIZED_ME"
 INITIALIZED_ME="yes"
 handle_result $? "$INITIALIZED_ME" "failed to reassign INITIALIZED_ME" "$debug"
 
 
 d_do show_config "$debug"  # show config prior to processing cmdline only at info/debug verbosity
-j_msg -${debug} -m "(BEFORE process_cmdline)"
+j_msg "-${debug}" -m "(BEFORE process_cmdline)"
 
 # note that without a defined command sequence and  the use of run_sequence
 # the INTERACTIVE, RESUME envinronment variables and their corresponding
@@ -145,7 +148,7 @@ j_msg -${debug} -m "(BEFORE process_cmdline)"
 process_cmdline "$@" || die "failed to process_cmdline"
 
 d_do show_config "$info"  # show config prior to processing cmdline only at info/debug verbosity
-j_msg -${info} -m "(AFTER process_cmdline)"
+j_msg "-${info}" -m "(AFTER process_cmdline)"
 
 # instead of calling run_sequence for interactive oversight of complex
 # processes, simple tasks can be coded directly, right here
diff --git a/dev-util/joetoolkit/joetoolkit/nextcloud_maintentance_clear_cache b/dev-util/joetoolkit/joetoolkit/nextcloud_maintentance_clear_cache
--- a/dev-util/joetoolkit/joetoolkit/nextcloud_maintentance_clear_cache
+++ b/dev-util/joetoolkit/joetoolkit/nextcloud_maintentance_clear_cache
@@ -1,4 +1,7 @@
 #!/bin/bash
+# Copyright 2025-2026 Joseph Brendler
+# SPDX-License-Identifier: GPL-3.0-or-later
+
 source /usr/sbin/script_header_joetoo
 
 #-----[ variables ]------------------------------------------
@@ -7,7 +10,7 @@ PN=${0##*/}   #  like =$(basename $0) but w/o subshell and function call
 
 if [ -f /etc/joetoolkit/BUILD ]; then . /etc/joetoolkit/BUILD; else BUILD="0.0.1"; fi
 
-[ -z $verbosity ] && verbosity=${notice}  # assign default if null; allow calling program to dictate
+[ -z "$verbosity" ] && verbosity="${notice}"  # assign default if null; allow calling program to dictate
 
 nextcloud_dir="/var/www/localhost/htdocs/myCloud"
 silent=">/dev/null 2>&1"
@@ -30,21 +33,21 @@ checkroot
 separator "$(hostname)" "${PN}-${BUILD}"
 
 old_dir=$(pwd)
-j_msg -${notice} -p -n "${BYon}Moving to ${BMon}${nextcloud_dir}${Boff}"
-cd ${nextcloud_dir} || die "failed to move to ${nextcloud_dir}"
-right_status $TRUE ${notice}
-j_msg -${info} -p "${BWon}pwd: ${LBon}$(pwd)${Boff}"
+j_msg "-${notice}" -p -n "${BYon}Moving to ${BMon}${nextcloud_dir}${Boff}"
+cd "${nextcloud_dir}" || die "failed to move to ${nextcloud_dir}"
+right_status $TRUE "${notice}"
+j_msg "-${info}" -p "${BWon}pwd: ${LBon}$(pwd)${Boff}"
 
 for ((i=0; i< ${#command_sequence[@]}; i++)) ; do
-    j_msg -${notice} -p -n "${BWon}running ${BGon}${msg_sequence[$i]}${Boff} ..."
+    j_msg "-${notice}" -p -n "${BWon}running ${BGon}${msg_sequence[$i]}${Boff} ..."
     eval "${command_sequence[$i]}" || die "failed: ${command_sequence[$i]}"
-    right_status $TRUE ${notice}
+    right_status $TRUE "${notice}"
 done
-j_msg -${notice} -mp ""  # newline
+j_msg "-${notice}" -mp ""  # newline
 
-j_msg -${notice} -p -n "${BYon}Moving back to ${BMon}${old_dir}${Boff}"
-cd ${nextcloud_dir} || die "failed to move to ${nextcloud_dir}"
-right_status $TRUE ${notice}
-j_msg -${info} -p "${BWon}pwd: ${LBon}$(pwd)${Boff}"
+j_msg "-${notice}" -p -n "${BYon}Moving back to ${BMon}${old_dir}${Boff}"
+cd "${nextcloud_dir}" || die "failed to move to ${nextcloud_dir}"
+right_status $TRUE "${notice}"
+j_msg "-${info}" -p "${BWon}pwd: ${LBon}$(pwd)${Boff}"
 
-j_msg -${notice} -p "${BGon}Done${Boff}"
+j_msg "-${notice}" -p "${BGon}Done${Boff}"
diff --git a/dev-util/joetoolkit/joetoolkit/nextcloud_upgrade b/dev-util/joetoolkit/joetoolkit/nextcloud_upgrade
--- a/dev-util/joetoolkit/joetoolkit/nextcloud_upgrade
+++ b/dev-util/joetoolkit/joetoolkit/nextcloud_upgrade
@@ -1,11 +1,13 @@
 #!/bin/bash
+# Copyright 2023-2026 Joseph Brendler
+# SPDX-License-Identifier: GPL-3.0-or-later
+
 # nextcloud_upgrade
-# joe brendler 6 August 2023
 #
 source /usr/sbin/script_header_joetoo
 new_version=""
 myCloud_dir="/var/www/localhost/htdocs/myCloud/"
-old_dir=$PWD
+old_dir="$PWD"
 
 #BUILD=0.1.3
 if [ -f /etc/joetoolkit/BUILD ]; then . /etc/joetoolkit/BUILD; else BUILD=0.1.4; fi
@@ -23,46 +25,46 @@ OCC_UP=$FALSE
 version_check()     # check the new ($1) and currently installed versions and set external result
 {
   new_ver="$1"
-  j_msg -${notice} -p "${BYon}Checing current version${Boff}"
-  filename=$(find ${myCloud_dir} -maxdepth 1 -iname '*nextcloud*')
-  cur_ver=${filename##*-}  # strip longest match for *- from the left - leaving version installed by webapp
+  j_msg "-${notice}" -p "${BYon}Checing current version${Boff}"
+  filename=$(find "${myCloud_dir}" -maxdepth 1 -iname '*nextcloud*')
+  cur_ver="${filename##*-}"  # strip longest match for *- from the left - leaving version installed by webapp
   # start output comparison line with new version info
-  j_msg -${notice} -p -n "Requested Version: ${new_ver}"
-  vercomp ${new_ver} ${cur_ver}; result=$?
+  j_msg "-${notice}" -p -n "Requested Version: ${new_ver}"
+  vercomp "${new_ver}" "${cur_ver}"; result=$?
   # print comparison indicator (< = >)
-  j_msg -${notice} -mp -n " $(show_result $result)"
+  j_msg "-${notice}" -mp -n " $(show_result $result)"
   # finish output line with comparison target info
-  j_msg -${notice} -p " ${cur_ver} (currently installed)"
-  j_msg -${notice} -p "result: $result"
+  j_msg "-${notice}" -p " ${cur_ver} (currently installed)"
+  j_msg "-${notice}" -p "result: $result"
 }
 
 webappconfig_upgrade()
 {
   new_ver="$1"
-  j_msg -${notice} -p "${BWon}About to upgrade with command:  [ ${BGon}webapp-config -d $(basename ${myCloud_dir}) -U nextcloud ${new_version} ${BWon}] ${BRon}CTRL-C to abort${Boff}"
+  j_msg "-${notice}" -p "${BWon}About to upgrade with command:  [ ${BGon}webapp-config -d $(basename ${myCloud_dir}) -U nextcloud ${new_version} ${BWon}] ${BRon}CTRL-C to abort${Boff}"
   sh_countdown 4
-  webapp-config -d $(basename ${myCloud_dir}) -U nextcloud ${new_ver}
+  webapp-config -d $(basename "${myCloud_dir}") -U nextcloud "${new_ver}"
 }
 
 occ_upgrade()
 {
-  cd ${myCloud_dir}
-  j_msg -${notice} -p "switched from ${old_dir} to $PWD"
-  j_msg -${notice} -p "do not forget to switch back to ${old_dir} when complete"
+  cd "${myCloud_dir}"
+  j_msg "-${notice}" -p "switched from ${old_dir} to $PWD"
+  j_msg "-${notice}" -p "do not forget to switch back to ${old_dir} when complete"
   echo
-  j_msg -${notice} -p "${BWon}About to upgrade with command:  [ ${BGon}sudo -u apache php ./occ upgrade ${BWon}] ${BRon}CTRL-C to abort${Boff}"
+  j_msg "-${notice}" -p "${BWon}About to upgrade with command:  [ ${BGon}sudo -u apache php ./occ upgrade ${BWon}] ${BRon}CTRL-C to abort${Boff}"
   sh_countdown 5
   sudo -u apache php ./occ upgrade
-  cd ${old_dir}
+  cd "${old_dir}"
 }
 
 double_check()
 {
-  j_msg -${notice} -p "${BYon}Currently configured as follows${Boff}"
-  j_msg -${notice} -m "${LBon} Currently installed nextcloud version.............: ${BWon}${cur_ver}${Boff}"
-  j_msg -${notice} -m "${LBon} Requested new nextcloud version...................: ${BWon}${new_ver}${Boff}"
-  j_msg -${notice} -m "${LBon} WEBAPP_UP (upgrade nextcloud with webapp-config)...: $(status_color ${WEBAPP_UP})$(TrueFalse ${WEBAPP_UP})${Boff}"
-  j_msg -${notice} -m "${LBon} OCC_UP (upgrade installed app with occ)............: $(status_color ${OCC_UP})$(TrueFalse ${OCC_UP})${Boff}"
+  j_msg "-${notice}" -p "${BYon}Currently configured as follows${Boff}"
+  j_msg "-${notice}" -m "${LBon} Currently installed nextcloud version.............: ${BWon}${cur_ver}${Boff}"
+  j_msg "-${notice}" -m "${LBon} Requested new nextcloud version...................: ${BWon}${new_ver}${Boff}"
+  j_msg "-${notice}" -m "${LBon} WEBAPP_UP (upgrade nextcloud with webapp-config)...: $(status_color ${WEBAPP_UP})$(TrueFalse ${WEBAPP_UP})${Boff}"
+  j_msg "-${notice}" -m "${LBon} OCC_UP (upgrade installed app with occ)............: $(status_color ${OCC_UP})$(TrueFalse ${OCC_UP})${Boff}"
   yns_prompt "${BMon}Continue?${Boff}"
 }
 
@@ -71,36 +73,36 @@ separator "nextcloud_upgrade-${BUILD}"
 checkroot
 [ $# -gt 1 -o $# -eq 0 ] && echo "please provide exactly one argument (new version #)" && exit 1
 new_version="$1"
-version_check ${new_version}
+version_check "${new_version}"
 
 # configure logical flags, to proceed as directed
-case ${result} in
+case "${result}" in
   0) # =
     response=""
     yns_prompt "Requested version is already installed by webapp-config. Continue or skip to occ upgrade?"
-    case ${response} in
-      [yY]*) j_msg -${notice} -p "Proceeding with reinstall..."; WEBAPP_UP=$TRUE; OCC_UP=$TRUE ;;
-      [nN]*) j_msg -${notice} -p "Exiting..."; WEBAPP_UP=$FALSE; OCC_UP=$FALSE ;;
-      [sS]*) j_msg -${notice} -p "Skipping webapp upgrade; continuing to occ upgrade..."; WEBAPP_UP=$FALSE; OCC_UP=$TRUE  ;;
-      *    ) j_msg -${err} "Invalid response to prompt [${response}]; exiting..."; exit 1 ;;
+    case "${response}" in
+      [yY]*) j_msg "-${notice}" -p "Proceeding with reinstall..."; WEBAPP_UP=$TRUE; OCC_UP=$TRUE ;;
+      [nN]*) j_msg "-${notice}" -p "Exiting..."; WEBAPP_UP=$FALSE; OCC_UP=$FALSE ;;
+      [sS]*) j_msg "-${notice}" -p "Skipping webapp upgrade; continuing to occ upgrade..."; WEBAPP_UP=$FALSE; OCC_UP=$TRUE  ;;
+      *    ) j_msg "-${err}" "Invalid response to prompt [${response}]; exiting..."; exit 1 ;;
     esac
     ;;
   1) # >
-    j_msg -${notice} -p "Proceeding with both webapp-config and occ upgrades..."
+    j_msg "-${notice}" -p "Proceeding with both webapp-config and occ upgrades..."
     WEBAPP_UP=$TRUE; OCC_UP=$TRUE
     ;;
   2) # <
     response=""
     yns_prompt "Are you sure you want to downgrade?"
-    case ${response} in
-      [yY]*) j_msg -${notice} -p "Proceeding with downgrade..."; WEBAPP_UP=$TRUE; OCC_UP=$TRUE ;;
-      [nN]*) j_msg -${notice} -p "Exiting..."; WEBAPP_UP=$FALSE; OCC_UP=$FALSE ;;
-      [sS]*) j_msg -${notice} -p "Skipping webapp upgrade; continuing to occ upgrade..."; WEBAPP_UP=$FALSE; OCC_UP=$TRUE  ;;
-      *    ) j_msg -${err} "Invalid response to prompt [${response}]; exiting..."; exit 1 ;;
+    case "${response}" in
+      [yY]*) j_msg "-${notice}" -p "Proceeding with downgrade..."; WEBAPP_UP=$TRUE; OCC_UP=$TRUE ;;
+      [nN]*) j_msg "-${notice}" -p "Exiting..."; WEBAPP_UP=$FALSE; OCC_UP=$FALSE ;;
+      [sS]*) j_msg "-${notice}" -p "Skipping webapp upgrade; continuing to occ upgrade..."; WEBAPP_UP=$FALSE; OCC_UP=$TRUE  ;;
+      *    ) j_msg "-${err}" "Invalid response to prompt [${response}]; exiting..."; exit 1 ;;
     esac
     ;;
   *) # <
-    j_msg -${err} "Invalid result from version_check() [${result}]; exiting"
+    j_msg "-${err}" "Invalid result from version_check() [${result}]; exiting"
     exit 1
     ;;
 esac
@@ -108,15 +110,15 @@ esac
 # double-check user comittment to contiue as directed
 response=""
 double_check
-case ${response} in
-  [yY]*) j_msg -${notice} -p "Proceeding..." ;;
-  [nNsS]*) j_msg -${notice} -p "Aborting at user's request..."; WEBAPP_UP=$FALSE; OCC_UP=$FALSE ;;
-  *    ) j_msg -${err} "Invalid response to prompt [${response}]; exiting..."; exit 1 ;;
+case "${response}" in
+  [yY]*) j_msg "-${notice}" -p "Proceeding..." ;;
+  [nNsS]*) j_msg "-${notice}" -p "Aborting at user's request..."; WEBAPP_UP=$FALSE; OCC_UP=$FALSE ;;
+  *    ) j_msg "-${err}" "Invalid response to prompt [${response}]; exiting..."; exit 1 ;;
 esac
 
 # execute the selected upgrade/downgrade steps
-[[ ${WEBAPP_UP} ]] && webappconfig_upgrade ${new_version}
+[[ ${WEBAPP_UP} ]] && webappconfig_upgrade "${new_version}"
 [[ ${OCC_UP} ]] && occ_upgrade
 
-j_msg -${notice} -p "All done"
+j_msg "-${notice}" -p "All done"
 exit 0
diff --git a/dev-util/joetoolkit/joetoolkit/resetMySqlRootPassword b/dev-util/joetoolkit/joetoolkit/resetMySqlRootPassword
--- a/dev-util/joetoolkit/joetoolkit/resetMySqlRootPassword
+++ b/dev-util/joetoolkit/joetoolkit/resetMySqlRootPassword
@@ -1,10 +1,13 @@
-#edit to pick a password, then save the text below to a file (/home/joe/mysql_init)
+#!/bin/bash
+# Copyright 2025-2026 Joseph Brendler
+# SPDX-License-Identifier: GPL-3.0-or-later
+
+# resetMySqlRootPassword - like it says; pick a password, then save, and run reset command
 #
-SET PASSWORD FOR 'root'@'localhost' = PASSWORD('new_password');
 
-# stop the mysql server:
 # /etc/init.d/mysql stop
-
+# create file /home/joe/mysql_init with this content -->///
+# "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('<password>');"
 #as root, issue the command:
 # mysqld_safe --init-file=/home/joe/mysql_init &
 #you should now be able to start mysql and login
@@ -12,3 +15,43 @@ SET PASSWORD FOR 'root'@'localhost' = PASSWORD('new_password');
 # mysql -u root -h localhost -p  (supply password chosen above in response to prompt)
 
 #see also -- http://dev.mysql.com/doc/refman/5.7/en/resetting-permissions.html
+
+
+source /usr/sbin/script_header_joetoo
+
+
+PN=${0##*/}   #  like =$(basename $0) but w/o subshell and function call
+
+if [ -f /etc/joetoolkit/BUILD ]; then . /etc/joetoolkit/BUILD; else BUILD="0.0.1"; fi
+
+[ -z "$verbosity" ] && verbosity=${notice}  # assign default if null; allow calling program to dictate
+
+#-----[ variables ]---------------------------------------------------------
+user="joe"
+
+#-----[ main script ]-------------------------------------------------------
+checkroot
+
+# stop the mysql server:
+j_msg "-${notice}" -p -n "Stopping mysql server"
+/etc/init.d/mysql stop &>/dev/null
+right_status $?
+
+result=""
+# get a new password and store it as part of mysql_init file
+if pass=$(ask_pass " $bin_key ${BWon}Enter a new root password for mysql:${Boff} "); then
+    echo "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('${pass}');" > "/home/${user}/mysql_init"
+    result=$?
+else
+    die "failed to set new password"
+fi
+handle_result $result "ok [${#pass}] char pwd" "" "$notice"
+
+# now reset the password
+j_msg "-${notice}" -p -n "Running mysqld_safe in the background, to reset password"
+mysqld_safe --init-file=/home/joe/mysql_init &>/dev/null & pid=$!
+handle_result $? "ran as pid [$pid]" "error" || die "failed to reset password"
+
+j_msg "-${notice}" -p -n "Restarting mysql server"
+/etc/init.d/mysql start &>/dev/null
+right_status $?
