dev-util/joetoolkit-1.0.8.tbz2 - bugfix tmux-workflow #2
Signed-off-by: JosephBrendler <joseph.brendler@gmail.com>

diff --git a/dev-util/joetoolkit/joetoolkit/tmux-workflow b/dev-util/joetoolkit/joetoolkit/tmux-workflow
--- a/dev-util/joetoolkit/joetoolkit/tmux-workflow
+++ b/dev-util/joetoolkit/joetoolkit/tmux-workflow
@@ -141,6 +141,7 @@ cmd_attach() {
     j_msg "-${debug}" -p "${BYon}(debug)${Boff} in ${FUNCNAME[0]} with arg(s) [$*]"
     # attach to session specified by $2 (default to highest #d)
     local session="${1:-$(latest_session)}" _a_result=0
+    local server_pid=""
     j_msg "-${debug}" -p "${BYon}(debug)${Boff} session: $session"
     # guard - validate session name
     case "$session" in
@@ -155,14 +156,15 @@ cmd_attach() {
     if ! LC_CTYPE=en_US.utf8 tmux -S "$SOCK_PATH" send-keys "j_msg -${notice} -p 'Attached successfully'" C-m ; then
         j_msg "-${warn}" -p "Unable to pre-position attached message"
     fi
-    # prepare to attach -- get pid in addition to session and sock above, so as to immunize against dynamic upgrade
+    # prepare to attach -- get pid in addition to session and SOCK_PATH above, so as to immunize against dynamic upgrade
     # of the tmux executable while the session is running (which will result in an attach failure
     # with the misleading message: "open terminal failed: not a terminal" but can be diagnosed by noting
     # /proc/<pid>/exe --> '/usr/bin/tmux (deleted)'
     # reference - https://github.com/tmux/tmux/wiki/Formats/
     # "a format is a string containing special directives contained in #{} which tmux will expand
     # (display-message -p prints the result rather than displaying it in the status line)
-    local server_pid=$(tmux -S "$sock" display-message -p '#{pid}')
+    if ! server_pid=$(tmux -S "$SOCK_PATH" display-message -p '#{pid}'); then
+        die "failed to determine tmux server pid for [$session]"; fi
     # Note: a tmux-workflow session should preferentially be attached using the same executable inode as its server
     # whenever the installed tmux executable has changed
     # ( -ef checks if two files have the same device and inode number )
@@ -174,7 +176,6 @@ cmd_attach() {
         # inode is the NOT same - tmux executable HAS changed since session started (attach with /proc/<pid>/exe)
         if LC_CTYPE=en_US.utf8 /proc/"$server_pid"/exe -S "$SOCK_PATH" attach -t "$session"; then
             _a_result=0; else _a_result=$?; fi
-
     fi
     # this wont run until user detaches from or kills from inside the session, so report detachment or failure to attach
     j_msg "-${notice}" -p -n "tmux result:"
@@ -242,7 +243,7 @@ latest_session() {
 
 cmd_info() {
     j_msg "-${notice}" -p "status of all running tmux-workflow servers"
-    local session="" pid="" created="" created_human=""
+    local session="" pid="" created="" created_human="" server_exe="" exe_state=""
     # iterate over all .sock files
     for sock in "${SOCK_DIR%/}/"*.sock ; do
         # check if tmux server is alive
@@ -254,14 +255,24 @@ cmd_info() {
             # https://github.com/tmux/tmux/wiki/Formats/
             # "a format is a string containing special directives contained in #{} which tmux will expand
             # (display-message -p prints the result rather than displaying it in the status line)
-            pid=$(tmux -S "$sock" display-message -p '#{pid}')
+            if ! pid=$(tmux -S "$sock" display-message -p '#{pid}'); then  die "failed to determine pid for [$session]"; fi
             # extract creation time
             created=$(tmux -S "$sock" display-message -p "#{session_created}")
+            # reformat date string in standard human readable form
             created_human=$(date --date="@${created}" "+%Y-%m-%d %H:%M:%S")
+            # determine the actual tmux executable status
+            if ! server_exe=$(readlink "/proc/$pid/exe"); then die "failed to get tmux executable from /proc/\$pid/exe"; fi
+            # check if /proc/<pid>/exe and tmux have the same inode and warn if not
+            if [ /proc/"$pid"/exe -ef "$(command -v tmux)" ]; then
+                exe_state="$bin_check_mark_button ${BGon}ok${Boff}"
+            else
+                exe_state="$bin_warning ${BRon}differs${Boff}"
+            fi
             # tmux can support multiple sessions, each with multiple windows, each with multiple panes
             # (but to stay simple, tmux-workflow creates tmux servers with --
             #  exactly one session, with one window, wtih one pane, with one shell, with one pid)
-            j_msg "-${notice}" -m "tmux server (socket): ${sock} | session: ${session} | pid: ${pid} | created: ${created_human}"
+            j_msg "-${notice}" -m "socket: ${sock} | session: ${session} | pid: ${pid} |"
+            j_msg "-${notice}" -m "   created: ${created_human} | exe: ${server_exe} (${exe_state})"
         fi
     done
 }
