joetoo-platform-meta-0.1.44.tbz2 - update scripts, add copyright/license info, start migration to joetoo-upstream
Signed-off-by: JosephBrendler <joseph.brendler@gmail.com>

diff --git a/joetoo-base/joetoo-platform-meta/tools/parallel-assemble-make-conf-all b/joetoo-base/joetoo-platform-meta/tools/parallel-assemble-make-conf-all
--- a/joetoo-base/joetoo-platform-meta/tools/parallel-assemble-make-conf-all
+++ b/joetoo-base/joetoo-platform-meta/tools/parallel-assemble-make-conf-all
@@ -1,8 +1,19 @@
 #!/bin/bash
-#
+# Copyright 2025-2026 Joseph Brendler
+# SPDX-License-Identifier: GPL-3.0-or-later
+##
 # use GNU parallel to assemble all make.conf files
 #
+# shellcheck source=/usr/sbin/script_header_joetoo
 source /usr/sbin/script_header_joetoo
+
+# source ui assets directly - to placate shellcheck
+# shellcheck source=/var/lib/joetoo/.joetoo_ui_asset_store
+source /var/lib/joetoo/.joetoo_ui_asset_store
+
+# source unicode header directly - to placate shellcheck
+# shellcheck source=/usr/sbin/script_header_joetoo_unicode
+source /usr/sbin/script_header_joetoo_unicode
 
 # experimental results with gmki91 (20 core alder lake i9 12000k)
 # -j	Runtime
@@ -23,13 +34,15 @@ source /usr/sbin/script_header_joetoo
 # 19	13.56 s	13.76 s	Slight jitter
 # 20	13.00 s	13.20 s	Best overall
 # set number of jobs here
-jobs=${1:-$(nproc)}
+jobs="${1:-$(nproc)}"
 
 # use a temp file to track progress of the parallel build
 joblog_file=$(mktemp /tmp/joetoo-parallel-assemble-make-conf-all-joblog.XXXXXX)
 
 # instead of nesting for loops, create two arrays to drive the input streams
-boards=( $(joetoo-sbc-list | awk '{print $1}') )
+declare -a boards=()
+# ingest null-delimited lines generated by awk's printf
+readarray -d '' -t boards < <( joetoo-sbc-list | awk '{printf "%s\0", $1}' )
 
 configs=(
     assemble-make-conf.headless.crossbuild.conf
@@ -45,13 +58,13 @@ msg="${BYon}$bin_hammer Running${_cmd_color} parallel ${_data_color}-j${jobs}${B
 msg+="QUIET${_op_color}=${BRon}\$TRUE ${_op_color}./${_func_color}assemble-make-conf"
 msg+="${Boff} for all joetoo-supported platforms and configs${Boff}"
 tw=$(termwidth)
-j_msg -${notice} -mp ""  # serverity-aware newline
+j_msg "-${notice}" -mp ""  # serverity-aware newline
 box_msg "$msg" $(( tw - ( tw / 4 ) ))
-j_msg -${notice} -mp ""  # serverity-aware newline
-j_msg -${notice} -p "${Con}this may take a minute or so; $(emoji_safe $uT_watch) please wait ...${Boff}"
-j_msg -${notice} -mp ""  # serverity-aware newline
+j_msg "-${notice}" -mp ""  # serverity-aware newline
+j_msg "-${notice}" -p "${Con}this may take a minute or so; $(emoji_safe $uT_watch) please wait ...${Boff}"
+j_msg "-${notice}" -mp ""  # serverity-aware newline
 
-old_v=$verbosity
+old_v="$verbosity"
 export QUIET=$TRUE
 export verbosity=0
 
@@ -59,23 +72,31 @@ export verbosity=0
 # ":::" is how GNU parallel separates its argument list input streams
 # send the entire parallel jobset to background with & to measure progress
 # set verbosity=0 (not QUIET=$TRUE which silences errors) to enable parallel io
-parallel --joblog "$joblog_file" -j${jobs} sudo verbosity=0 ./assemble-make-conf \
-    {1} {2} ::: "${boards[@]}" ::: "${configs[@]}" &
+parallel --joblog "$joblog_file" -j "${jobs}" sudo verbosity=0 ./assemble-make-conf \
+    "{1}" "{2}" ::: "${boards[@]}" ::: "${configs[@]}" &
 par_pid=$!
 
 # loop to track progress with progress bar (kill -0 just means does pid exist)
-while kill -0 $par_pid 2>/dev/null; do
-    jobs_done=$(($(wc -l < "${joblog_file}") - 1))   # subtract header
+while kill -0 "$par_pid" 2>/dev/null; do
+    line_count=$(wc -l < "${joblog_file}")
+    if [ "$line_count" -gt 1 ]; then
+        jobs_done=$(( line_count - 1 ))   # subtract header
+    else
+        jobs_done=0
+    fi
     progress_inline "$jobs_done" "$total"
     sleep 0.2
 done  # progress bar
+wait "$par_pid"
+result=$?
+right_status "$result" "$notice" || die "parallel make.conf generation failed"
 
 # final update to progressbar
 jobs_done=$(($(wc -l < "${joblog_file}") - 1))
 progress_inline "$jobs_done" "$total"
 
 export QUIET=$FALSE
-export verbosity=$old_v
+export verbosity="$old_v"
 
 rm -f "$joblog_file"
 
